//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRJTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartment
    {
        public int DepartmentId { get; set; }
        public Nullable<int> ReportId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public string DepartmentName { get; set; }
    
        public virtual tblReport tblReport { get; set; }
        public virtual tblReport tblReport1 { get; set; }
        public virtual tblTeacher tblTeacher { get; set; }
        public virtual tblTeacher tblTeacher1 { get; set; }
    }
}
