//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRJTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblReport()
        {
            this.tblDepartments = new HashSet<tblDepartment>();
            this.tblDepartments1 = new HashSet<tblDepartment>();
        }
    
        public Nullable<int> TimeId { get; set; }
        public Nullable<int> AttendanceId { get; set; }
        public int ReportId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string StudentReport { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual tblAttendance tblAttendance { get; set; }
        public virtual tblCourse tblCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDepartment> tblDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDepartment> tblDepartments1 { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
